image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build
  artifacts:
    paths:
      - .next/

test:
  stage: test
  script:
    - yarn test
