image: node:latest

stages:
  - build
  - test

# See https://github.com/vercel/next.js/blob/master/errors/no-cache.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .next/cache/
    - node_modules/

build:
  stage: build
  before_script:
    - yarn
  script:
    - yarn build
  artifacts:
    paths:
      - .next/

test:
  stage: test
  script:
    - yarn test
